# Generated by Django 4.2.5 on 2023-10-03 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='status',
        ),
        migrations.AddField(
            model_name='advuser',
            name='dolzn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dolzn', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен')], default=1, max_length=50, verbose_name='Статус проекта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkOnProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dat', models.DateField(verbose_name='Дата')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typework', verbose_name='Вид работы')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Работа по проекту',
                'verbose_name_plural': 'Работы по проектам',
            },
        ),
        migrations.CreateModel(
            name='WorkerInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
                ('worker', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник в проекте',
                'verbose_name_plural': 'Сотрудники в проекте',
            },
        ),
    ]
